# NumPy Tutorial
[Source](https://github.com/PoLun-Wang/Learn_NumPy)

# Lesson 3: Basic calculation in NumPy(addition, subtraction, multiplication and division)

## 加、減、次方
**基礎運算-1**
* 加、減、次方的計算非常直覺好懂，分別使用『 + 、 – 、 ** 』就可以了。
* 例如：加、減、次方都可以直接做單一數值的同加、同減、次方。

In [2]:
import numpy as np

In [37]:
np.set_printoptions()  # reset print options

print('維度相同的矩陣相加、減:')
# 維度相同的矩陣相加、減
a = np.array( [6, 7, 8, 9] )
b = np.arange( 4 )
c = a - b
print("a=>{0}".format(a))
print("b=>{0}".format(b))
print("c=>{0}".format(c))
 
 
print('\n同加、同減一個數值:')
# 同加、同減一個數值
a += 5
print("a=>{0}".format(a))
b -= 5
print("b=>{0}".format(b))
 
 
print('\n次方：')
# d是b的2次方
# d is squared of b.
d = b**2
print("d=>{0}".format(d))

維度相同的矩陣相加、減:
a=>[6 7 8 9]
b=>[0 1 2 3]
c=>[6 6 6 6]

同加、同減一個數值:
a=>[11 12 13 14]
b=>[-5 -4 -3 -2]

次方：
d=>[25 16  9  4]


## 同除、同乘特定數
**基礎運算-2**
* `矩陣(matrix)`同乘上某個特定`純量(scalar)`也很簡單，就直接相乘就好了！

In [39]:
a = np.arange(5)
b = np.arange(10, 5, -1)
print("a=>{0}".format(a))
print("b=>{0}".format(b))
print("\n同除:")
# c等於a同除以2
c = a / 2
print("c=>{0}".format(c))
 
print("\n同乘:")
# d等於b同乘以2
d = b * 2
print("d=>{0}".format(d))

a=>[0 1 2 3 4]
b=>[10  9  8  7  6]

同除:
c=>[0.  0.5 1.  1.5
 2. ]

同乘:
d=>[20 18 16 14 12]


<h2>矩陣運算</h2>
<p>$A=
\begin{bmatrix}
1 & 2 \\
3& 4
\end{bmatrix},\space
B=
\begin{bmatrix}
5 & 6 \\
7 & 8
\end{bmatrix}
$</p>
<p><strong>矩陣乘法：</strong>
$A\times B=
\begin{bmatrix}
\begin{bmatrix} 1 \times 5 + 2 \times 7 \end{bmatrix} & \begin{bmatrix} 1 \times 6 + 2 \times 8 \end{bmatrix} \\
\begin{bmatrix} 3 \times 5 + 4 \times 7 \end{bmatrix} & \begin{bmatrix} 3 \times 6 + 4 \times 8 \end{bmatrix}
\end{bmatrix}
$</p>
<p>$=
\begin{bmatrix}
\begin{bmatrix} 5 + 14 \end{bmatrix} & \begin{bmatrix} 6 + 16 \end{bmatrix} \\
\begin{bmatrix} 15 + 28 \end{bmatrix} & \begin{bmatrix} 18 + 32 \end{bmatrix} \\
\end{bmatrix}
$</p>
<p>$=
\begin{bmatrix}
19 & 22 \\
43 & 50
\end{bmatrix}
$</p>
<p><strong>矩陣相對應位置相乘：</strong>

\begin{bmatrix}
1\times 5 & 2\times 6 \\
3\times 7 & 4\times 8
\end{bmatrix}=
\begin{bmatrix}
5 & 12 \\
21 & 32
\end{bmatrix}

In [40]:
# 矩陣相乘
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("A, B相乘(矩陣乘法) =>\n{0}".format(A.dot(B)))
print()
print("A, B相對應位置相乘=>\n{0}".format(A*B))

A, B相乘(矩陣乘法) =>
[[19 22]
 [43 50]]

A, B相對應位置相乘=>
[[ 5 12]
 [21 32]]


## 取代
**取代**
* 這個也很常用到喔，像是有時候要把矩陣裡面NaN的數值取代成0的時候就很好用！
* 舉例：判斷陣列元素值小於等於0的元素，把那些元素的數值取代成1

In [41]:
# 印出陣列中小於等於0的元素
e = np.array([5, -1, 3, 9, 0])
print("陣列e裡面哪幾個位置的元素值小於等於零?:{0}".format(e<=0))
 
# 把小於等於0的元素取代成1
e[e<=0] = 1
print("把小於等於0的元素取代成1=>{0}".format(e))

陣列e裡面哪幾個位置的元素值小於等於零?:[False  True False
 False  True]
把小於等於0的元素取代成1=>[5 1 3 9 1]


## 陣列元素的型別
**常犯錯誤**
* 因為NumPy太好用了，導致有時候甚至會忽略兩個要做運算的陣列型別根本不符，最後就會出錯～哈
* 用下列例子給大家了解這種狀況：

In [3]:
## Operations: += *=
a = np.ones((2, 3), dtype=np.float)
b = np.random.random( (2,3) )
a *= 5
print("a=>\n{0}".format(a))
print("b=>\n{0}".format(b))
b += a
print("b += a: b=>\n{0}".format(b))
 
a += b
print("a += b: a=>\n{0}".format(a))

a=>
[[5. 5. 5.]
 [5. 5. 5.]]
b=>
[[0.82756764 0.55367925 0.40450138]
 [0.6677403  0.5847374  0.37026601]]
b += a: b=>
[[5.82756764 5.55367925 5.40450138]
 [5.6677403  5.5847374  5.37026601]]
a += b: a=>
[[10.82756764 10.55367925 10.40450138]
 [10.6677403  10.5847374  10.37026601]]


* 如果把上面範例第二行程式的 np.float 改成 np.int 就會出錯喔！
* 下列程式第11行：硬是用型別為int的矩陣加上一個型別為float的矩陣，肯定會出錯的吧！
```
UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'
```

In [4]:
## Operations: += *=
a = np.ones((2, 3), dtype=np.int)
b = np.random.random( (2,3) )
a *= 5
print("a=>\n{0}".format(a))
print("b=>\n{0}".format(b))
b += a
print("b += a: b=>\n{0}".format(b))
 
a += b
print("a += b: a=>\n{0}".format(a))

a=>
[[5 5 5]
 [5 5 5]]
b=>
[[0.12294656 0.89689834 0.9390135 ]
 [0.98076049 0.29205396 0.69613955]]
b += a: b=>
[[5.12294656 5.89689834 5.9390135 ]
 [5.98076049 5.29205396 5.69613955]]


UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

## 矩陣的屬性
**常用方法-1**
* NumPy矩陣本身在初始化之後就內建一些好用的方法！
* `sum`：矩陣加總
* `min`：矩陣最小值
* `max`：矩陣最大值
* `mean`：矩陣平均值

In [8]:
## Methods: sum, min, max, mean
a = np.random.random((3, 3))
print("a=>\n{0}\n".format(a))
print("sum=>{0}\nmax=>{1}\nmin=>{2}\nmean=>{3}".format(a.sum(), a.max(), a.min(), a.mean()))

a=>
[[0.67762919 0.03247199 0.37042681]
 [0.17634316 0.39180384 0.16709503]
 [0.89976409 0.91469205 0.60366088]]

sum=>4.233887046623988
max=>0.9146920489208394
min=>0.032471993558459644
mean=>0.47043189406933206


## 矩陣的一些方法
**常用方法-2**
* `sum`：axis=0或1  算是進階用法，可以指定要加總的維度是哪一個
* `cumsum`：這是可以拿來對陣列值做出累計加總的效果，可以用在一維陣列上，數值就可以直接拿來畫出累計趨勢圖喔～

In [9]:
b = np.arange(12).reshape(2, 6)
print("b=>\n{0}".format(b))
 
print()
# 加總每一欄(column)
print("b.sum(axis=0)=>{0}".format(b.sum(axis=0)))
 
print()
# 加總每一列(row)
print("b.sum(axis=0)=>{0}".format(b.sum(axis=1)))
 
print()
revenu = np.round(np.random.random((1,12)) * 100, 0)
print("revenu=>\n{0}".format(revenu))
 
print()
# 累計加總(每一項數值等於自己加上前一項)
print("Cumulative Sum of revenu=>\n{0}".format(revenu.cumsum()))

b=>
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

b.sum(axis=0)=>[ 6  8 10 12 14 16]

b.sum(axis=0)=>[15 51]

revenu=>
[[96. 36.  0. 24. 68. 56. 41. 31. 15. 38. 87.  7.]]

Cumulative Sum of revenu=>
[ 96. 132. 132. 156. 224. 280. 321. 352. 367. 405. 492. 499.]


**常用方法-3**
* np.sqrt：矩陣內所有元素開平方根
* np.exp：矩陣內所有元素進行Exponential function(e)運算
* np.add：矩陣或陣列相加

In [12]:
B = np.arange(3)
print("B=> {0}".format(B))
B_exp = np.exp(B)
print("B_exp=> {0}".format(B_exp))
 
B_sqrt = np.sqrt(B)
print("B_sqrt=> {0}".format(B_sqrt))
 
C = np.array([2, 1, 0])
print("np.add(B, C)=> {0}".format(np.add(B, C)))

B=> [0 1 2]
B_exp=> [1.         2.71828183 7.3890561 ]
B_sqrt=> [0.         1.         1.41421356]
np.add(B, C)=> [2 2 2]


還有很多常用的方法：
all, any, apply_along_axis, argmax, argmin, argsort, average, bincount, ceil, clip, conj, corrcoef, cov, cross, cumprod, cumsum, diff, dot, floor, inner, inv, lexsort, max, maximum, mean, median, min, minimum, nonzero, outer, prod, re, round, sort, std, sum, trace, transpose, var, vdot, vectorize, where